services:
  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: csv_car
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432